from app.domain.plans import plan_catalog


TEXTS = {
    "ru": {
        "buy": "🚀 Купить VPN",
        "profile": "👤 Мой профиль",
        "setup": "📲 Инструкция",
        "support": "💬 Поддержка",
        "menu_title": "🏠 <b>Главное меню</b>\n\nВыберите действие:",
        "choose_language": "🌐 <b>Выберите язык</b>\n\nПо умолчанию используется русский.",
        "choose_plan": "🚀 <b>Выберите тариф</b>\n\nЧем дольше период, тем выгоднее стоимость.",
        "choose_payment": "Выберите удобный способ оплаты:",
        "pay": "💳 Оплатить",
        "check_payment": "✅ Проверить оплату",
        "other_method": "🔁 Другой способ",
        "back_menu": "🏠 Главное меню",
        "back": "🏠 Назад",
        "back_plans": "← Назад к тарифам",
        "activate_promo": "🎟 Активировать промокод",
        "referrals": "🎁 Рефералка",
        "change_lang": "🌐 Language",
        "info": "ℹ️ Информация",
        "qr_code": "📱 QR код",
        "qr_unavailable": "❌ У вас нет активной подписки.",
        "qr_caption": "📱 QR код подписки",
        "profile_title": "👤 <b>Мой профиль</b>",
        "username": "Telegram",
        "subscription": "Подписка",
        "no_subscription": "нет активной подписки",
        "active_until": "активна до",
        "sub_link": "Ссылка",
        "promo_prompt": "🎟 <b>Промокод</b>\n\nОтправьте промокод одним сообщением.",
        "promo_not_found": "⚠️ Промокод не найден или уже не активен.",
        "promo_used": "⚠️ Вы уже активировали этот промокод.",
        "promo_checkout_only": "ℹ️ Этот промокод доступен для оплаты на сайте, но не даёт бонус в боте.",
        "promo_ok_plan": "🎉 Промокод активирован. Подписка выдана на <b>{months} мес.</b>",
        "invoice_created": "✅ <b>Счёт создан</b>",
        "after_pay": "1. Нажмите «Оплатить».\n2. Завершите оплату.\n3. Вернитесь сюда и нажмите «Проверить оплату».",
        "payment_pending": "⏳ <b>Оплата пока не подтверждена</b>\n\nЕсли вы уже оплатили, подождите 10-20 секунд и нажмите кнопку ещё раз.",
        "payment_ok": "🎉 <b>Оплата подтверждена</b>",
        "support_text": "💬 <b>Поддержка</b>\n\nЕсли что-то не получилось с оплатой или подключением — нажмите кнопку ниже.",
        "plan_1": "⚡ 1 месяц - ${price}",
        "plan_3": "🔥 3 месяца - ${price}",
        "plan_12": "👑 12 месяцев - ${price}",
        "no_active_subscription_long": "❌ У вас нет активной подписки.",
        "subscription_inactive": "⏳ Подписка не активна.\nДата окончания: <b>{expiry}</b>\n\nМожно продлить доступ в разделе «Купить VPN».",
        "subscription_active": "✅ <b>Подписка активна</b>\n\n🗓 Осталось дней: <b>{days}</b>\n⏱ Действует до: <b>{date}</b>",
        "syncing": "⏳ Ссылка ещё синхронизируется. Нажмите «Обновить» через минуту.",
        "start": "👋 Привет{name}! Это <b>VEXND VPN</b>.\n\nЗдесь можно купить подписку, оплатить удобным способом и сразу получить ссылку для подключения.\n\nВыберите действие ниже:",
        "setup_text": "📲 <b>Как подключиться</b>\n\n1. Установите клиент: <b>v2RayTun</b>, <b>FlClashX</b> или <b>Happ</b>.\n2. Откройте «Мой профиль» и скопируйте subscription URL.\n3. Импортируйте ссылку в приложении или отсканируйте QR-код.",
        "payment_title": "💳 <b>Оплата подписки</b>",
        "plan": "Тариф",
        "amount": "Сумма",
        "method": "Способ",
        "balance": "Баланс",
        "balance_title": "💰 <b>Внутренний баланс</b>",
        "balance_topup": "Пополнить",
        "balance_buy": "Оплатить подписку с баланса",
        "balance_current": "Текущий баланс",
        "balance_choose_amount": "Выберите сумму пополнения:",
        "balance_choose_method": "Выберите способ пополнения:",
        "balance_topup_ok": "Баланс пополнен.",
        "balance_topup_pending": "Платёж ещё не подтверждён.",
        "balance_pay_ok": "Подписка оплачена с баланса.",
        "balance_not_enough": "⚠️ Недостаточно средств на внутреннем балансе.",
        "balance_topup_hint": "После оплаты вернитесь и нажмите «Проверить оплату».",
        "invoice_error": "⚠️ Не удалось создать счёт.\n\nПопробуйте другой способ оплаты или напишите в поддержку, если ошибка повторится.",
        "invoice_missing": "⚠️ Счёт не найден. Создайте новый счёт из меню покупки.",
        "sub_activated": "Подписка активирована.",
        "info_text": "ℹ️ <b>Информация</b>\n\nЮридические документы и публичные страницы VEXND:",
        "legal": "📄 Пользовательское соглашение",
        "faq": "❓ FAQ",
        "setup_link": "📲 Инструкция",
        "referral_title": "🎁 <b>Реферальная программа</b>",
        "referral_text": "Приглашайте друзей: им +3 дня к первой оплате, вам +5 дней после их первой оплаты.",
        "referral_link_label": "Ваша ссылка",
        "referral_invited": "Приглашено",
        "referral_paid": "Оплатили",
        "referral_invited_by": "Вас пригласил",
        "referral_bonus_note": "Бонусы начисляются один раз и только после первой успешной оплаты приглашённого друга.",
        "referral_share_hint": "Не открывайте ссылку сами, просто отправьте её другу.",
        "referral_captured": "🎁 Рефералка привязана. После первой оплаты вы получите +3 дня, а пригласивший — +5 дней.",
        "referral_invalid": "⚠️ Реферальная ссылка недействительна.",
        "referral_already_used": "ℹ️ Рефералка уже привязана к вашему аккаунту.",
        "referral_too_late": "ℹ️ Рефералка действует только до первой оплаты.",
        "telegram_login_ok": "✅ Подтверждение получено. Вернитесь на сайт: вход или привязка аккаунта уже готовы.",
        "telegram_auth_request_login": "🔐 <b>Вход через Telegram</b>\n\nСайт просит подтвердить вход в ваш аккаунт через этого бота.\n\nЕсли это вы, нажмите кнопку ниже.",
        "telegram_auth_request_link": "🔗 <b>Привязка Telegram</b>\n\nСайт просит привязать этот Telegram к вашему веб-аккаунту.\n\nЕсли это вы, подтвердите действие кнопкой ниже.",
        "telegram_auth_request_password_reset": "🔑 <b>Сброс пароля</b>\n\nСайт просит подтвердить сброс пароля для вашего аккаунта.\n\nЕсли это вы, нажмите кнопку ниже.",
        "telegram_auth_confirm": "✅ Подтвердить",
        "telegram_auth_decline": "✖️ Отказаться",
        "telegram_auth_declined": "❌ Запрос отклонён. Если вход всё ещё нужен, вернитесь на сайт и начните заново.",
        "telegram_login_challenge_not_found": "⚠️ Код входа не найден или уже истёк. Откройте сайт и получите новый код.",
        "telegram_login_telegram_not_linked": "⚠️ Не удалось подтвердить вход: Telegram-аккаунт не связан с внутренним профилем.",
        "telegram_login_challenge_invalid": "⚠️ Код подтверждения повреждён. Запросите новый код на сайте.",
        "telegram_login_merge_requires_support": "⚠️ Этот Telegram уже связан с другим полноценным аккаунтом. Для безопасного объединения напишите в поддержку.",
        "telegram_login_merge_failed": "⚠️ Не удалось объединить аккаунты автоматически. Напишите в поддержку, и мы поможем.",
        "telegram_login_user_not_found": "⚠️ Профиль для входа не найден. Попробуйте ещё раз позже.",
        "telegram_login_declined": "❌ Подтверждение отклонено в Telegram. Вернитесь на сайт и начните снова, если вход всё ещё нужен.",
        "telegram_generated_password": "🔑 <b>Пароль для входа на сайте</b>\n\nМы сгенерировали пароль для вашего аккаунта. Сохраните его в надёжном месте:\n<tg-spoiler>{password}</tg-spoiler>",
        "admin_panel": "🛠 Админ-панель",
        "admin_title": "🛠 <b>Админ-панель ссылок</b>",
        "admin_empty": "Ссылок пока нет. Создайте первую ссылку кнопкой ниже.",
        "admin_create_link": "➕ Создать ссылку",
        "admin_refresh_stats": "🔄 Обновить статистику",
        "admin_create_prompt": "Отправьте название новой ссылки одним сообщением.\n\nНапример: <code>Instagram / блогер 1</code>",
        "admin_create_success": "✅ <b>Ссылка создана</b>\n\n<b>Название:</b> {name}\n<b>Переходов:</b> {total}\n<b>Уникальных:</b> {unique}\n<b>Ссылка:</b>\n<code>{url}</code>",
        "admin_name_empty": "⚠️ Название не должно быть пустым.",
        "admin_name_too_long": "⚠️ Название слишком длинное. Максимум 80 символов.",
        "admin_access_denied": "⛔ У вас нет доступа к админ-панели.",
        "admin_stats_line": "• <b>{name}</b>\nПереходов: <b>{total}</b> | Уникальных: <b>{unique}</b>",
    },
    "en": {
        "buy": "🚀 Buy VPN",
        "profile": "👤 My profile",
        "setup": "📲 Setup guide",
        "support": "💬 Support",
        "menu_title": "🏠 <b>Main menu</b>\n\nChoose an action:",
        "choose_language": "🌐 <b>Choose language</b>\n\nRussian is selected by default.",
        "choose_plan": "🚀 <b>Choose a plan</b>\n\nLonger plans give you a better price.",
        "choose_payment": "Choose a payment method:",
        "pay": "💳 Pay",
        "check_payment": "✅ Check payment",
        "other_method": "🔁 Other method",
        "back_menu": "🏠 Main menu",
        "back": "🏠 Back",
        "back_plans": "← Back to plans",
        "activate_promo": "🎟 Activate promo code",
        "referrals": "🎁 Referrals",
        "change_lang": "🌐 Язык",
        "info": "ℹ️ Information",
        "qr_code": "📱 QR code",
        "qr_unavailable": "❌ You do not have an active subscription.",
        "qr_caption": "📱 Subscription QR code",
        "profile_title": "👤 <b>My profile</b>",
        "username": "Telegram",
        "subscription": "Subscription",
        "no_subscription": "no active subscription",
        "active_until": "active until",
        "sub_link": "Link",
        "promo_prompt": "🎟 <b>Promo code</b>\n\nSend your promo code in one message.",
        "promo_not_found": "⚠️ Promo code was not found or is no longer active.",
        "promo_used": "⚠️ You have already used this promo code.",
        "promo_checkout_only": "ℹ️ This promo code is available for website checkout, but it has no bot bonus.",
        "promo_ok_plan": "🎉 Promo code activated. Subscription issued for <b>{months} mo.</b>",
        "invoice_created": "✅ <b>Invoice created</b>",
        "after_pay": "1. Tap “Pay”.\n2. Complete the payment.\n3. Return here and tap “Check payment”.",
        "payment_pending": "⏳ <b>Payment is not confirmed yet</b>\n\nIf you have already paid, wait 10-20 seconds and try again.",
        "payment_ok": "🎉 <b>Payment confirmed</b>",
        "support_text": "💬 <b>Support</b>\n\nIf you need help with payment or setup, tap the button below.",
        "plan_1": "⚡ 1 month - ${price}",
        "plan_3": "🔥 3 months - ${price}",
        "plan_12": "👑 12 months - ${price}",
        "no_active_subscription_long": "❌ You do not have an active subscription.",
        "subscription_inactive": "⏳ Subscription is inactive.\nExpires: <b>{expiry}</b>\n\nYou can renew access in “Buy VPN”.",
        "subscription_active": "✅ <b>Subscription is active</b>\n\n🗓 Days left: <b>{days}</b>\n⏱ Active until: <b>{date}</b>",
        "syncing": "⏳ The link is still syncing. Tap “Refresh” in a minute.",
        "start": "👋 Hi{name}! This is <b>VEXND VPN</b>.\n\nHere you can buy a subscription, pay securely, and instantly receive your connection link.\n\nChoose an action below:",
        "setup_text": "📲 <b>How to connect</b>\n\n1. Install a client: <b>v2RayTun</b>, <b>FlClashX</b>, or <b>Happ</b>.\n2. Open “My profile” and copy your subscription URL.\n3. Import the link in the app or scan the QR code.",
        "payment_title": "💳 <b>Subscription payment</b>",
        "plan": "Plan",
        "amount": "Amount",
        "method": "Method",
        "balance": "Balance",
        "balance_title": "💰 <b>Internal balance</b>",
        "balance_topup": "Top up",
        "balance_buy": "Pay subscription from balance",
        "balance_current": "Current balance",
        "balance_choose_amount": "Choose a top-up amount:",
        "balance_choose_method": "Choose a top-up method:",
        "balance_topup_ok": "Balance credited.",
        "balance_topup_pending": "The payment is not confirmed yet.",
        "balance_pay_ok": "Subscription paid from balance.",
        "balance_not_enough": "⚠️ Not enough funds on your internal balance.",
        "balance_topup_hint": "After payment, return here and tap “Check payment”.",
        "invoice_error": "⚠️ Could not create an invoice.\n\nTry another payment method or contact support if the issue persists.",
        "invoice_missing": "⚠️ Invoice not found. Create a new invoice from the purchase menu.",
        "sub_activated": "Subscription activated.",
        "info_text": "ℹ️ <b>Information</b>\n\nLegal documents and public VEXND pages:",
        "legal": "📄 Terms of service",
        "faq": "❓ FAQ",
        "setup_link": "📲 Setup guide",
        "referral_title": "🎁 <b>Referral program</b>",
        "referral_text": "Invite friends: they get +3 days on their first payment, and you get +5 days after their first payment.",
        "referral_link_label": "Your link",
        "referral_invited": "Invited",
        "referral_paid": "Paid",
        "referral_invited_by": "Invited by",
        "referral_bonus_note": "Bonuses are granted once and only after your invited friend completes the first successful payment.",
        "referral_share_hint": "Do not open the link yourself, just send it to a friend.",
        "referral_captured": "🎁 Referral link attached. After your first payment you get +3 days, and the inviter gets +5 days.",
        "referral_invalid": "⚠️ Referral link is invalid.",
        "referral_already_used": "ℹ️ A referral is already attached to your account.",
        "referral_too_late": "ℹ️ Referral links work only before the first payment.",
        "telegram_login_ok": "✅ Confirmed. Return to the website: your sign-in or account link is ready.",
        "telegram_auth_request_login": "🔐 <b>Sign in with Telegram</b>\n\nThe website is asking to confirm sign-in to your account through this bot.\n\nIf this was you, tap the button below.",
        "telegram_auth_request_link": "🔗 <b>Link Telegram</b>\n\nThe website is asking to link this Telegram account to your web account.\n\nIf this was you, confirm the action below.",
        "telegram_auth_request_password_reset": "🔑 <b>Password reset</b>\n\nThe website is asking to confirm a password reset for your account.\n\nIf this was you, tap the button below.",
        "telegram_auth_confirm": "✅ Confirm",
        "telegram_auth_decline": "✖️ Decline",
        "telegram_auth_declined": "❌ Request declined. If you still want to continue, go back to the website and start again.",
        "telegram_login_challenge_not_found": "⚠️ The sign-in code was not found or has expired. Open the website and request a new one.",
        "telegram_login_telegram_not_linked": "⚠️ Could not confirm sign-in: this Telegram account is not linked to an internal profile.",
        "telegram_login_challenge_invalid": "⚠️ The confirmation code is invalid. Request a new one on the website.",
        "telegram_login_merge_requires_support": "⚠️ This Telegram account is already linked to another full account. Please contact support for a safe merge.",
        "telegram_login_merge_failed": "⚠️ Could not merge accounts automatically. Contact support and we will help.",
        "telegram_login_user_not_found": "⚠️ The profile for sign-in was not found. Please try again later.",
        "telegram_login_declined": "❌ Confirmation was declined in Telegram. Return to the website and start again if you still need to sign in.",
        "telegram_generated_password": "🔑 <b>Password for website sign-in</b>\n\nWe generated a password for your account. Keep it in a safe place:\n<tg-spoiler>{password}</tg-spoiler>",
        "admin_panel": "🛠 Admin panel",
        "admin_title": "🛠 <b>Tracked links admin</b>",
        "admin_empty": "No links yet. Create the first one using the button below.",
        "admin_create_link": "➕ Create link",
        "admin_refresh_stats": "🔄 Refresh stats",
        "admin_create_prompt": "Send the name of the new link in one message.\n\nExample: <code>Instagram / blogger 1</code>",
        "admin_create_success": "✅ <b>Link created</b>\n\n<b>Name:</b> {name}\n<b>Starts:</b> {total}\n<b>Unique:</b> {unique}\n<b>Link:</b>\n<code>{url}</code>",
        "admin_name_empty": "⚠️ Name cannot be empty.",
        "admin_name_too_long": "⚠️ Name is too long. Maximum is 80 characters.",
        "admin_access_denied": "⛔ You do not have access to the admin panel.",
        "admin_stats_line": "• <b>{name}</b>\nStarts: <b>{total}</b> | Unique: <b>{unique}</b>",
    },
}

TEXTS["ru"].update(
    {
        "buy": "💳 Оплатить",
        "profile": "📊 Моя подписка",
        "setup": "🚀 Подключить",
        "support": "⚙️ Помощь",
        "menu_title": "🏠 <b>Главное меню</b>\n\nВыберите нужный раздел:",
        "start": "👋 Привет{name}!\n\n⚡ Подключение в 1 клик без настроек\n🌍 Зарубежные сервисы доступны\n🇷🇺 Работают русские сервисы\n\n👇 Нажмите «Подключить»",
        "choose_plan": "💳 <b>Оплатить</b>\n\nВыберите тариф:",
        "payment_title": "💳 <b>Оплатить</b>",
        "plan_1": "⚡ 1 мес — $3.99",
        "plan_3": "🔥 3 мес — $10.99",
        "plan_12": "👑 12 мес — $34.99",
        "subscription_title": "📊 <b>Моя подписка</b>",
        "subscription_expiry": "📅 Срок действия",
        "subscription_traffic": "📦 Трафик",
        "subscription_status": "🟢 Статус",
        "subscription_status_active": "Активна",
        "subscription_status_inactive": "Неактивна",
        "subscription_refresh": "🔄 Обновить данные",
        "subscription_connect": "🚀 Подключить",
        "subscription_qr": "📱 Получить QR",
        "subscription_buy": "💳 Купить подписку",
        "subscription_missing": "Подписка не найдена.",
        "traffic_unknown": "данные синхронизируются",
        "connect_title": "🚀 <b>Подключить VPN</b>",
        "connect_need_subscription": "Подписка не найдена.",
        "connect_choose_device": "Шаг 1. Выберите устройство:",
        "connect_choose_desktop": "Шаг 2. Выберите систему:",
        "connect_choose_client": "Шаг 2. Выберите клиент для {device}:",
        "connect_install_step": "Шаг 3. Установите <b>{client}</b> на {device}.",
        "connect_add_step": "Шаг 4. Добавьте подписку в <b>{client}</b>.",
        "connect_done": "Шаг 5. 📡 Откройте приложение и нажмите «Подключиться».",
        "connect_copy_sent": "Ссылка на подписку отправлена отдельным сообщением.",
        "connect_link_missing": "Ссылка на подписку пока не готова. Подождите немного и попробуйте ещё раз.",
        "done": "✅ Готово",
        "device_ios": "🍏 iPhone",
        "device_android": "🤖 Android",
        "device_pc": "💻 ПК",
        "device_windows": "🖥️ Windows",
        "device_macos": "💻 MacOS",
        "download_app": "📥 Скачать приложение",
        "installed_app": "✅ Я установил",
        "add_to_app": "🚀 Добавить в приложение",
        "copy_link": "📋 Скопировать ссылку",
        "help_title": "⚙️ <b>Помощь</b>",
        "help_text": "Здесь собраны быстрые ссылки на поддержку, ответы на частые вопросы и юридическую информацию.",
        "help_support": "💬 Поддержка",
        "help_support_text": "Если нужна помощь с оплатой, подпиской или подключением, напишите в поддержку.",
        "help_faq": "❓ FAQ",
        "help_faq_text": "Здесь собраны ответы на частые вопросы по сервису и подключению.",
        "help_legal": "📚 Юридическая информация",
        "legal_title": "📚 <b>Юридическая информация</b>",
        "legal_text": "В этом разделе собраны юридические документы и правила использования сервиса.",
        "legal_terms": "📄 Пользовательское соглашение",
        "legal_privacy": "🔐 Конфиденциальность",
        "legal_refund": "💸 Возвраты",
        "legal_aup": "🛡️ AUP",
        "bonus_days": "Бонус",
        "referral_bonus_value": "+5 дней за оплатившего друга",
        "share_link": "📤 Поделиться",
        "loading": "⏳ <b>Загрузка...</b>",
        "trial": "🎁 Пробный доступ",
        "trial_offer": "🎁 1 день бесплатно",
        "trial_started": "🎉 Пробный доступ на 1 день активирован.\n\nПодписка уже выдана и появилась в вашем профиле.",
        "trial_used": "ℹ️ Пробный доступ уже использован или недоступен для этого аккаунта.",
        "trial_reminder_soon": "⏰ Пробный доступ закончится менее чем через {hours} ч.\n\nЕсли хотите сохранить доступ без перерыва, продлите подписку заранее.",
        "trial_reminder_expired": "⌛ Пробный доступ закончился.\n\nЧтобы продолжить пользоваться VPN, выберите платный тариф.",
        "subscription_reminder_soon": "⏰ Подписка закончится менее чем через {hours} ч.\n\nПродлите доступ заранее, чтобы не было перерыва.",
        "subscription_reminder_expired": "⌛ Срок подписки закончился.\n\nЧтобы вернуть доступ, продлите подписку в боте.",
    }
)

TEXTS["en"].update(
    {
        "buy": "💳 Pay",
        "profile": "📊 My subscription",
        "setup": "🚀 Connect",
        "support": "⚙️ Help",
        "menu_title": "🏠 <b>Main menu</b>\n\nChoose a section:",
        "start": "👋 Hi{name}!\n\n⚡ One-click setup without manual configuration\n🌍 Foreign services are available\n🇷🇺 Russian services also work\n\n👇 Tap “Connect”",
        "choose_plan": "💳 <b>Pay</b>\n\nChoose a plan:",
        "payment_title": "💳 <b>Pay</b>",
        "plan_1": "⚡ 1 month — $3.99",
        "plan_3": "🔥 3 months — $10.99",
        "plan_12": "👑 12 months — $34.99",
        "subscription_title": "📊 <b>My subscription</b>",
        "subscription_expiry": "📅 Expiry",
        "subscription_traffic": "📦 Traffic",
        "subscription_status": "🟢 Status",
        "subscription_status_active": "Active",
        "subscription_status_inactive": "Inactive",
        "subscription_refresh": "🔄 Refresh data",
        "subscription_connect": "🚀 Connect",
        "subscription_qr": "📱 Get QR",
        "subscription_buy": "💳 Buy subscription",
        "subscription_missing": "Subscription not found.",
        "traffic_unknown": "data is syncing",
        "connect_title": "🚀 <b>Connect VPN</b>",
        "connect_need_subscription": "Subscription not found.",
        "connect_choose_device": "Step 1. Choose your device:",
        "connect_choose_desktop": "Step 2. Choose your system:",
        "connect_choose_client": "Step 2. Choose a client for {device}:",
        "connect_install_step": "Step 3. Install <b>{client}</b> on {device}.",
        "connect_add_step": "Step 4. Add your subscription to <b>{client}</b>.",
        "connect_done": "Step 5. 📡 Open the app and tap “Connect”.",
        "connect_copy_sent": "The subscription link was sent in a separate message.",
        "connect_link_missing": "The subscription link is not ready yet. Please wait a bit and try again.",
        "done": "✅ Done",
        "device_ios": "🍏 iPhone",
        "device_android": "🤖 Android",
        "device_pc": "💻 PC",
        "device_windows": "🖥️ Windows",
        "device_macos": "💻 MacOS",
        "download_app": "📥 Download app",
        "installed_app": "✅ I installed it",
        "add_to_app": "🚀 Add to app",
        "copy_link": "📋 Copy link",
        "help_title": "⚙️ <b>Help</b>",
        "help_text": "Quick links to support, frequently asked questions, and legal information are collected here.",
        "help_support": "💬 Support",
        "help_support_text": "If you need help with payment, subscription, or setup, contact support.",
        "help_faq": "❓ FAQ",
        "help_faq_text": "This section contains answers to common questions about the service and setup.",
        "help_legal": "📚 Legal",
        "legal_title": "📚 <b>Legal</b>",
        "legal_text": "This section contains the service's legal documents and usage policies.",
        "legal_terms": "📄 Terms of Service",
        "legal_privacy": "🔐 Privacy Policy",
        "legal_refund": "💸 Refund Policy",
        "legal_aup": "🛡️ Acceptable Use",
        "bonus_days": "Bonus",
        "referral_bonus_value": "+5 days for each invited friend who pays",
        "share_link": "📤 Share",
        "loading": "⏳ <b>Loading...</b>",
        "trial": "🎁 Trial access",
        "trial_offer": "🎁 1 day free",
        "trial_started": "🎉 Your 1-day trial has been activated.\n\nThe subscription is already issued and available in your profile.",
        "trial_used": "ℹ️ Trial access has already been used or is not available for this account.",
        "trial_reminder_soon": "⏰ Your trial will expire in less than {hours}h.\n\nIf you want uninterrupted access, renew your subscription in advance.",
        "trial_reminder_expired": "⌛ Your trial has expired.\n\nChoose a paid plan to keep using the VPN.",
        "subscription_reminder_soon": "⏰ Your subscription will expire in less than {hours}h.\n\nRenew it in advance to avoid downtime.",
        "subscription_reminder_expired": "⌛ Your subscription has expired.\n\nRenew it in the bot to restore access.",
    }
)

BOT_PLAN_CATALOG: dict[int, dict[str, str]] = {
    months: {
        "label_ru": f"{months} мес",
        "label_en": f"{months} month" if months == 1 else f"{months} months",
        "price": str(plan["price"]),
    }
    for months, plan in sorted(plan_catalog().items())
}

CONNECT_CLIENTS: dict[str, list[dict[str, str]]] = {
    "ios": [
        {
            "code": "happ",
            "name": "Happ",
            "url_ru": "https://apps.apple.com/ru/app/happ-proxy-utility-plus/id6746188973",
            "url_global": "https://apps.apple.com/app/happ-proxy-utility/id6504287215",
        },
        {
            "code": "v2raytun",
            "name": "v2RayTun",
            "url": "https://apps.apple.com/app/v2raytun/id6476628951",
        },
    ],
    "android": [
        {
            "code": "v2raytun",
            "name": "v2RayTun",
            "url": "https://play.google.com/store/apps/details?id=com.v2raytun.android",
        },
        {
            "code": "flclashx",
            "name": "FlClashX",
            "url": "https://github.com/pluralplay/FlClashX/releases/download/v0.3.2/FlClashX-android-universal.apk",
        },
        {
            "code": "happ",
            "name": "Happ",
            "url": "https://play.google.com/store/apps/details?id=com.happproxy&pcampaignid=web_share",
        },
    ],
    "windows": [
        {
            "code": "flclashx",
            "name": "FlClashX",
            "url": "https://github.com/pluralplay/FlClashX/releases/latest/download/FlClashX-windows-amd64-setup.exe",
        },
        {
            "code": "v2raytun",
            "name": "v2RayTun",
            "url": "https://storage.v2raytun.com/v2RayTun_Setup.exe",
        },
        {
            "code": "happ",
            "name": "Happ",
            "url": "https://github.com/Happ-proxy/happ-desktop/releases/latest/download/setup-Happ.x64.exe",
        },
    ],
    "macos": [
        {
            "code": "flclashx",
            "name": "FlClashX",
            "url": "https://github.com/pluralplay/FlClashX/releases/download/v0.3.2/FlClashX-macos-arm64.dmg",
        },
        {
            "code": "v2raytun",
            "name": "v2RayTun",
            "url": "https://apps.apple.com/app/v2raytun/id6476628951",
        },
        {
            "code": "happ",
            "name": "Happ",
            "url_ru": "https://apps.apple.com/ru/app/happ-proxy-utility-plus/id6746188973",
            "url_global": "https://apps.apple.com/app/happ-proxy-utility/id6504287215",
        },
    ],
}

PAYMENT_METHODS = {
    "balance": {
        "label": "Balance · Внутренний счёт",
        "provider": "balance",
        "env": (),
    },
    "cryptobot": {
        "label": "CryptoBot · Криптовалюты",
        "provider": "cryptobot",
        "env": ("CRYPTO_PAY_API_TOKEN",),
    },
    "crystal": {
        "label": "CrystalPay · Lolz + Крипта",
        "provider": "crystalpay",
        "env": ("CRYSTALPAY_AUTH_LOGIN", "CRYSTALPAY_AUTH_SECRET"),
    },
    "platega": {
        "label": "Platega · СБП",
        "provider": "platega",
        "env": ("PLATEGA_MERCHANT_ID", "PLATEGA_SECRET"),
    },
    "heleket": {
        "label": "Heleket · Криптовалюты",
        "provider": "heleket",
        "env": ("HELEKET_MERCHANT_ID", "HELEKET_API_KEY"),
    },
}
